"""baseline schema

Revision ID: 2d783ead6088
Revises: 
Create Date: 2026-06-30 09:05:13.764327
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '2d783ead6088'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_branch', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('counters',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('namespace', sa.Text(), nullable=False),
    sa.Column('current_value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'namespace')
    )
    op.create_table('epics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('section', sa.Text(), nullable=False),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'key', name='uq_epic_project_key'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_epics_project_id'), 'epics', ['project_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'endpoint', 'key', name='uq_idempotency')
    )
    op.create_index(op.f('ix_idempotency_keys_project_id'), 'idempotency_keys', ['project_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'key', name='uq_tag_project_key')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('epic_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('todo', 'in_progress', 'blocked', 'deferred', 'done', 'superseded', 'cancelled', name='task_status'), nullable=False),
    sa.Column('priority', sa.Enum('P0', 'P1', 'P2', 'P3', name='priority'), nullable=True),
    sa.Column('component', sa.Text(), nullable=True),
    sa.Column('proof_cmd', sa.Text(), nullable=True),
    sa.Column('status_note', sa.Text(), nullable=True),
    sa.Column('section', sa.Text(), nullable=False),
    sa.Column('owner', sa.Text(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('superseded_by_task_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['epic_id'], ['epics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by_task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('ix_tasks_claim', 'tasks', ['project_id', 'status', 'priority', 'position'], unique=False)
    op.create_index('ix_tasks_owner', 'tasks', ['project_id', 'owner'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index('uq_task_project_key', 'tasks', ['project_id', 'key'], unique=True, postgresql_where=sa.text('key IS NOT NULL'))
    op.create_table('chain_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('started_by', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_chain_runs_project_id'), 'chain_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_chain_runs_task_id'), 'chain_runs', ['task_id'], unique=False)
    op.create_table('commit_refs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('sha', sa.Text(), nullable=False),
    sa.Column('repo', sa.Text(), nullable=True),
    sa.Column('test_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'sha', name='uq_commit_task_sha')
    )
    op.create_index(op.f('ix_commit_refs_task_id'), 'commit_refs', ['task_id'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.Text(), nullable=True),
    sa.Column('agent', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('consequences', sa.Text(), nullable=True),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['decisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_decisions_project_id'), 'decisions', ['project_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('agent', sa.Text(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_project_time', 'events', ['project_id', 'created_at'], unique=False)
    op.create_table('leases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('agent', sa.Text(), nullable=False),
    sa.Column('state', sa.Enum('active', 'released', 'expired', 'completed', name='lease_state'), nullable=False),
    sa.Column('acquired_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leases_task_id'), 'leases', ['task_id'], unique=False)
    op.create_index('uq_one_active_lease', 'leases', ['task_id'], unique=True, postgresql_where=sa.text("state = 'active'"))
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('namespace', sa.Text(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('reserved_by', sa.Text(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'namespace', 'value', name='uq_reservation_value')
    )
    op.create_index(op.f('ix_reservations_project_id'), 'reservations', ['project_id'], unique=False)
    op.create_table('task_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('src_task_id', sa.Integer(), nullable=False),
    sa.Column('dst_task_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('blocks', 'supersedes', 'relates', 'follow_up', name='relation_kind'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('src_task_id <> dst_task_id', name='ck_relation_self'),
    sa.ForeignKeyConstraint(['dst_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['src_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('src_task_id', 'dst_task_id', 'kind', name='uq_relation')
    )
    op.create_index(op.f('ix_task_relations_dst_task_id'), 'task_relations', ['dst_task_id'], unique=False)
    op.create_index(op.f('ix_task_relations_src_task_id'), 'task_relations', ['src_task_id'], unique=False)
    op.create_table('task_tags',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'tag_id')
    )
    op.create_table('chain_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.Text(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('agent', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('skip_justification', sa.Text(), nullable=True),
    sa.Column('output_ref', sa.Text(), nullable=True),
    sa.CheckConstraint("status <> 'skipped' OR skip_justification IS NOT NULL", name='ck_chainstep_skip_justified'),
    sa.ForeignKeyConstraint(['run_id'], ['chain_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'step_name', name='uq_chainstep_run_name')
    )
    op.create_index(op.f('ix_chain_steps_run_id'), 'chain_steps', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chain_steps_run_id'), table_name='chain_steps')
    op.drop_table('chain_steps')
    op.drop_table('task_tags')
    op.drop_index(op.f('ix_task_relations_src_task_id'), table_name='task_relations')
    op.drop_index(op.f('ix_task_relations_dst_task_id'), table_name='task_relations')
    op.drop_table('task_relations')
    op.drop_index(op.f('ix_reservations_project_id'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_index('uq_one_active_lease', table_name='leases', postgresql_where=sa.text("state = 'active'"))
    op.drop_index(op.f('ix_leases_task_id'), table_name='leases')
    op.drop_table('leases')
    op.drop_index('ix_events_project_time', table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_decisions_project_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_commit_refs_task_id'), table_name='commit_refs')
    op.drop_table('commit_refs')
    op.drop_index(op.f('ix_chain_runs_task_id'), table_name='chain_runs')
    op.drop_index(op.f('ix_chain_runs_project_id'), table_name='chain_runs')
    op.drop_table('chain_runs')
    op.drop_index('uq_task_project_key', table_name='tasks', postgresql_where=sa.text('key IS NOT NULL'))
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index('ix_tasks_owner', table_name='tasks')
    op.drop_index('ix_tasks_claim', table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('tags')
    op.drop_index(op.f('ix_idempotency_keys_project_id'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_epics_project_id'), table_name='epics')
    op.drop_table('epics')
    op.drop_table('counters')
    op.drop_table('projects')
    op.drop_table('agents')
    # ### end Alembic commands ###
