#!/usr/bin/env python3
"""copy_backend.py — one-off backlog copy/sync between storage backends (SLS-10).

Move a project's backlog between the two Spec Server storage backends
(PostgreSQL <-> DynamoDB) so a repo can flip ``STORAGE_BACKEND`` without losing
data. This is a **standalone operator tool**, not app runtime code.

Design — reuse the storage layer, no bespoke schema knowledge (mostly)
---------------------------------------------------------------------
The elegant core: instantiate BOTH backends behind the SAME
``app.storage.StorageBackend`` interface and copy entities through the neutral
frozen DTOs (``app/storage/dto.py``). Reading the backlog therefore needs zero
knowledge of either physical schema — ``list_projects`` / ``list_tasks`` / ... do
the enumeration and hand back DTOs; the matching ``create_*`` / ``upsert_*`` /
``add_*`` methods write them to the destination.

Two things the neutral *interface* cannot express, so they use a small, clearly
isolated backend-specific path (the ``_pg_*`` / ``_ddb_*`` helpers):

  * **Numbered resources** — counters have no "set to value N" method (the live
    API only ever *increments*), and reservation rows have no "insert with an
    explicit value" method. We must land these directly so the destination's
    NEXT ``reserve_number`` continues monotonically. We set each counter to the
    source's ``current_value`` (never lowering it).
  * **Relations & chain-runs** — the read interface exposes no ``list_relations``
    / ``list_chain_runs``. We enumerate them per-backend, then WRITE them back
    through the neutral API (``add_relation`` / ``create_chain_run`` +
    ``upsert_chain_step``).

What is preserved, and what is NOT
----------------------------------
Copied faithfully: slugs, human keys, titles, descriptions, status, priority,
component, proof_cmd, section, position, tags, task<->epic links, task<->task
relations, reservation values + counter high-water marks (so numbering keeps
climbing), agent roster, epic/task note *bodies*, commit SHAs, event/decision
*content*.

Cannot be perfectly preserved (the destination generates them, or the neutral
write API resets them) — reported honestly per run:

  * ``public_id`` — regenerated by every ``create_*`` (a fresh UUID on the dest).
  * ``version`` — reset to 1 (``create_task`` starts fresh; optimistic-lock
    history does not survive).
  * timestamps (``created_at`` / ``updated_at`` / ``completed_at`` / note+commit
    times / chain start/finish) — set to copy-time on the destination.
  * ``owner`` / ``lease_expires_at`` — dropped (a mid-flight claim/lease is NOT
    migrated; run the copy against a quiesced source).
  * DB integer ids — internal to Postgres, meaningless across backends.
  * reservation -> task linkage — the ``ReservationDTO`` carries no task ref, so
    the audit row's task association is not reconstructed.

Idempotency & safety
--------------------
  * ``--dry-run`` READS the source only and prints per-entity counts of what
    WOULD be copied. It never touches the destination.
  * A real run is re-runnable: keyed entities (projects/epics/tasks/agents,
    reservations by value, commits by sha, counters by value) are skipped or
    max-merged if they already exist on the destination — never duplicated, and
    nothing is ever DELETED from either side.
  * CAVEAT: append-only rows with no natural key — epic/task **notes**,
    **events**, **decisions**, and **tasks that have no human key** — cannot be
    de-duplicated on a second run and WILL be appended again. Run once, or run
    into a fresh destination. This is surfaced in the final report.

Process/coexistence constraint
------------------------------
``PostgresBackend`` uses Flask-SQLAlchemy's single global ``db.session`` (one
engine per process), so **at most one side may be postgres**. That covers the
real use case — a backend switch is postgres<->dynamodb. A postgres->postgres
copy is a job for ``pg_dump``/``pg_restore``; this tool refuses it.

Configuration (environment)
---------------------------
Each side reads its own prefixed config so both can be set simultaneously:

  Postgres side (whichever of source/dest is ``postgres``):
    SRC_DATABASE_URL   / DEST_DATABASE_URL
        e.g. postgresql+psycopg://spec:spec@localhost:5432/specserver

  DynamoDB side (whichever of source/dest is ``dynamodb``):
    SRC_DYNAMODB_TABLE / DEST_DYNAMODB_TABLE           (default: spec-server)
    SRC_DYNAMODB_ENDPOINT_URL / DEST_DYNAMODB_ENDPOINT_URL
        set for DynamoDB Local, e.g. http://localhost:8000; unset for real AWS
    SRC_AWS_REGION / DEST_AWS_REGION                   (default: AWS_REGION or us-east-1)

  AWS credentials come from the ambient boto3 default chain
  (AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY/AWS_PROFILE). Both DynamoDB sides
  therefore share one credential set — cross-ACCOUNT dynamo->dynamo copies are
  out of scope (run the tool once per account, or use a single profile).

Examples
--------
Postgres -> DynamoDB (one project), preview first:

    export SRC_DATABASE_URL=postgresql+psycopg://spec:spec@localhost:5432/specserver
    export DEST_DYNAMODB_TABLE=spec-server
    export DEST_DYNAMODB_ENDPOINT_URL=http://localhost:8000
    export AWS_ACCESS_KEY_ID=local AWS_SECRET_ACCESS_KEY=local AWS_REGION=us-east-1
    python scripts/copy_backend.py --source postgres --dest dynamodb \
        --project spec-server --dry-run
    python scripts/copy_backend.py --source postgres --dest dynamodb --project spec-server

DynamoDB -> Postgres (all projects):

    export SRC_DYNAMODB_TABLE=spec-server SRC_DYNAMODB_ENDPOINT_URL=http://localhost:8000
    export DEST_DATABASE_URL=postgresql+psycopg://spec:spec@localhost:5432/specserver
    python scripts/copy_backend.py --source dynamodb --dest postgres --all
"""
from __future__ import annotations

import argparse
import os
import sys
from dataclasses import dataclass, field

# Make ``import app`` work when run as ``python scripts/copy_backend.py``.
_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)


# --------------------------------------------------------------------------- #
# Backend construction
# --------------------------------------------------------------------------- #
@dataclass
class Backend:
    """A configured source/dest endpoint behind the StorageBackend interface."""
    role: str          # "source" | "dest"
    kind: str          # "postgres" | "dynamodb"
    impl: object       # a StorageBackend (PostgresBackend / DynamoBackend)
    app: object = None       # Flask app (postgres only) — for context teardown
    ctx: object = None       # pushed app context (postgres only)

    @property
    def is_pg(self) -> bool:
        return self.kind == "postgres"

    @property
    def is_ddb(self) -> bool:
        return self.kind == "dynamodb"


def _require_env(name: str) -> str:
    val = os.environ.get(name)
    if not val:
        sys.exit(f"error: environment variable {name} is required for this copy.")
    return val


def build_backend(role: str, kind: str) -> Backend:
    """Instantiate a backend for ``role`` ("source"/"dest") of type ``kind``."""
    prefix = "SRC" if role == "source" else "DEST"

    if kind == "postgres":
        # Postgres uses the global Flask-SQLAlchemy session, so we bind it via a
        # real Flask app. Config reads DATABASE_URL/STORAGE_BACKEND from env at
        # import time, so set them BEFORE importing the factory.
        url = _require_env(f"{prefix}_DATABASE_URL")
        os.environ["DATABASE_URL"] = url
        os.environ["STORAGE_BACKEND"] = "postgres"
        from app import create_app  # lazy: after env is set

        app = create_app()
        ctx = app.app_context()
        ctx.push()
        return Backend(role=role, kind=kind, impl=app.storage, app=app, ctx=ctx)

    if kind == "dynamodb":
        table = os.environ.get(f"{prefix}_DYNAMODB_TABLE", "spec-server")
        endpoint = os.environ.get(f"{prefix}_DYNAMODB_ENDPOINT_URL")
        region = os.environ.get(
            f"{prefix}_AWS_REGION", os.environ.get("AWS_REGION", "us-east-1")
        )
        from app.storage.dynamo import DynamoBackend  # lazy

        impl = DynamoBackend(table=table, endpoint_url=endpoint, region=region)
        return Backend(role=role, kind=kind, impl=impl)

    sys.exit(f"error: unknown backend kind {kind!r}")


# --------------------------------------------------------------------------- #
# Reporting
# --------------------------------------------------------------------------- #
@dataclass
class EntityStat:
    copied: int = 0
    skipped: int = 0
    failed: int = 0
    would: int = 0


@dataclass
class Report:
    dry_run: bool
    stats: dict = field(default_factory=dict)
    warnings: list = field(default_factory=list)

    def _s(self, entity: str) -> EntityStat:
        return self.stats.setdefault(entity, EntityStat())

    def add(self, entity, *, copied=0, skipped=0, failed=0, would=0):
        s = self._s(entity)
        s.copied += copied
        s.skipped += skipped
        s.failed += failed
        s.would += would

    def warn(self, msg: str):
        self.warnings.append(msg)

    def render(self) -> str:
        lines = []
        header = "entity              would" if self.dry_run else \
            "entity              copied  skipped  failed"
        lines.append(header)
        lines.append("-" * len(header))
        for entity in ENTITY_ORDER:
            if entity not in self.stats:
                continue
            s = self.stats[entity]
            if self.dry_run:
                lines.append(f"{entity:<18}  {s.would:>5}")
            else:
                lines.append(
                    f"{entity:<18}  {s.copied:>6}  {s.skipped:>7}  {s.failed:>6}"
                )
        if self.warnings:
            lines.append("")
            lines.append(f"warnings ({len(self.warnings)}):")
            for w in self.warnings[:50]:
                lines.append(f"  - {w}")
            if len(self.warnings) > 50:
                lines.append(f"  ... and {len(self.warnings) - 50} more")
        return "\n".join(lines)


ENTITY_ORDER = [
    "projects", "agents", "epics", "epic_notes", "tasks",
    "commits", "task_notes", "relations",
    "reservations", "counters", "events", "decisions", "chain_runs",
]


# --------------------------------------------------------------------------- #
# Copier
# --------------------------------------------------------------------------- #
class Copier:
    def __init__(self, src: Backend, dest: Backend, report: Report,
                 verbose: bool = False):
        self.src = src
        self.dest = dest
        self.report = report
        self.dry_run = report.dry_run
        self.verbose = verbose
        # neutral errors, imported once
        from app.storage.errors import (
            BackendUnavailable, Conflict, NotFound, VersionConflict,
        )
        self._Conflict = Conflict
        self._NotFound = NotFound
        self._VersionConflict = VersionConflict
        self._BackendUnavailable = BackendUnavailable

    # ---- small helpers ------------------------------------------------- #
    def _log(self, msg: str):
        if self.verbose:
            print(msg, file=sys.stderr)

    def _write_each(self, entity: str, items: list, write_fn):
        """Apply ``write_fn`` to each item, tallying copied/skipped/failed.

        ``write_fn`` returns "copied" or "skipped". Conflict/VersionConflict are
        treated as an idempotent skip (already present on the dest); anything
        else counts as failed and is recorded as a warning.
        """
        if self.dry_run:
            self.report.add(entity, would=len(items))
            return
        for it in items:
            try:
                outcome = write_fn(it)
                self.report.add(entity, **{outcome: 1})
            except (self._Conflict, self._VersionConflict):
                self.report.add(entity, skipped=1)
            except Exception as exc:  # noqa: BLE001 — degrade gracefully per item
                self.report.add(entity, failed=1)
                self.report.warn(f"{entity}: {type(exc).__name__}: {exc}")
                self._log(f"[fail] {entity}: {exc}")

    def _all_tasks(self, backend, slug: str) -> list:
        out, offset, limit = [], 0, 500
        while True:
            page = backend.list_tasks(slug, {"offset": offset, "limit": limit})
            out.extend(page)
            if len(page) < limit:
                return out
            offset += limit

    def _all_events(self, backend, slug: str) -> list:
        out, offset, limit = [], 0, 500
        while True:
            page = backend.list_events(slug, {"offset": offset, "limit": limit})
            out.extend(page)
            if len(page) < limit:
                return out
            offset += limit

    # ---- entity copies ------------------------------------------------- #
    def copy_project(self, slug: str):
        p = self.src.impl.get_project(slug)

        def write(_):
            data = {
                "slug": p.slug, "name": p.name, "description": p.description,
                "default_branch": p.default_branch,
            }
            self.dest.impl.create_project(data)
            return "copied"

        self._write_each("projects", [p], write)

    def copy_agents(self, slug: str):
        agents = self.src.impl.list_agents(slug)

        def write(a):
            self.dest.impl.upsert_agent(slug, {
                "slug": a.slug, "display_name": a.display_name, "kind": a.kind,
            })
            return "copied"

        self._write_each("agents", agents, write)

    def copy_epics(self, slug: str):
        epics = self.src.impl.list_epics(slug)

        def write(e):
            self.dest.impl.create_epic(slug, {
                "key": e.key, "title": e.title, "description": e.description,
                "section": e.section, "position": e.position,
            })
            return "copied"

        self._write_each("epics", epics, write)
        return epics

    def copy_epic_notes(self, slug: str, epics: list):
        notes = []
        for e in epics:
            for n in self.src.impl.list_epic_notes(slug, e.key):
                notes.append((e.key, n))

        def write(item):
            ekey, n = item
            self.dest.impl.append_epic_note(slug, ekey, {
                "body": n.body, "author": n.author,
            })
            return "copied"

        self._write_each("epic_notes", notes, write)

    def copy_tasks(self, slug: str, tasks: list):
        def write(t):
            data = {
                "key": t.key, "title": t.title, "description": t.description,
                "status": t.status.value,
                "priority": t.priority.value if t.priority else None,
                "component": t.component, "proof_cmd": t.proof_cmd,
                "section": t.section, "position": t.position,
                "epic_key": t.epic_key, "tags": list(t.tags),
            }
            self.dest.impl.create_task(slug, data)
            if t.key is None:
                # keyless tasks cannot be de-duplicated on a re-run
                self.report.warn(
                    f"tasks: '{t.title[:40]}' has no human key — not re-run safe"
                )
            return "copied"

        self._write_each("tasks", tasks, write)

    def copy_commits(self, slug: str, tasks: list):
        commits = []
        for t in tasks:
            ident = t.key or None
            for c in t.commits:
                commits.append((ident, t.title, c))

        def write(item):
            ident, title, c = item
            if ident is None:
                self.report.warn(f"commits: task '{title[:40]}' keyless — skipped")
                return "skipped"
            self.dest.impl.add_commit(slug, ident, {
                "sha": c.sha, "repo": c.repo, "test_summary": c.test_summary,
            })
            return "copied"

        self._write_each("commits", commits, write)

    def copy_task_notes(self, slug: str, tasks: list):
        notes = []
        for t in tasks:
            ident = t.key or None
            for n in t.notes:
                notes.append((ident, t.title, n))

        def write(item):
            ident, title, n = item
            if ident is None:
                self.report.warn(f"task_notes: task '{title[:40]}' keyless — skipped")
                return "skipped"
            self.dest.impl.append_task_note(slug, ident, {
                "body": n.body, "author": n.author,
            })
            return "copied"

        self._write_each("task_notes", notes, write)

    def copy_relations(self, slug: str, tasks: list):
        rels = _read_relations(self.src, slug, tasks)

        def write(r):
            if not r["src_key"] or not r["dst_key"]:
                self.report.warn(
                    f"relations: {r['kind']} touches a keyless task — skipped"
                )
                return "skipped"
            self.dest.impl.add_relation(slug, r["src_key"], r["dst_key"], r["kind"])
            return "copied"

        self._write_each("relations", rels, write)

    def copy_reservations(self, slug: str):
        rows = self.src.impl.list_reservations(slug, None)

        def write(r):
            return _write_reservation(
                self.dest, slug, r.namespace, r.value, r.reserved_by,
                r.note, r.created_at,
            )

        self._write_each("reservations", rows, write)

    def copy_counters(self, slug: str):
        counters = self.src.impl.list_counters(slug)

        def write(c):
            _set_counter(self.dest, slug, c.namespace, c.current_value)
            return "copied"

        self._write_each("counters", counters, write)

    def copy_events(self, slug: str):
        events = self._all_events(self.src.impl, slug)

        def write(e):
            self.dest.impl.create_event(slug, {
                "event_type": e.event_type, "agent": e.agent,
                "message": e.message, "payload": e.payload or {},
            })
            return "copied"

        self._write_each("events", events, write)

    def copy_decisions(self, slug: str):
        decisions = self.src.impl.list_decisions(slug)

        def write(d):
            self.dest.impl.create_decision(slug, {
                "key": d.key, "title": d.title, "decision": d.decision,
                "context": d.context, "consequences": d.consequences,
                "agent": d.agent,
            })
            return "copied"

        self._write_each("decisions", decisions, write)

    def copy_chain_runs(self, slug: str, tasks: list):
        runs = _read_chain_runs(self.src, slug, tasks)

        def write(run):
            if not run["task_key"]:
                self.report.warn("chain_runs: run on a keyless task — skipped")
                return "skipped"
            created = self.dest.impl.create_chain_run(
                slug, run["task_key"], run["started_by"]
            )
            for step in run["steps"]:
                self.dest.impl.upsert_chain_step(slug, created.public_id,
                                                 step["step_name"], step)
            if run["status"] and run["status"] != "running":
                self.dest.impl.update_chain_run(slug, created.public_id,
                                                run["status"])
            return "copied"

        self._write_each("chain_runs", runs, write)

    # ---- per-project driver ------------------------------------------- #
    def copy_project_all(self, slug: str):
        self._log(f"== project {slug} ==")
        self.copy_project(slug)
        self.copy_agents(slug)
        epics = self.copy_epics(slug)
        self.copy_epic_notes(slug, epics)
        tasks = self._all_tasks(self.src.impl, slug)
        self.copy_tasks(slug, tasks)
        self.copy_commits(slug, tasks)
        self.copy_task_notes(slug, tasks)
        self.copy_relations(slug, tasks)
        self.copy_reservations(slug)
        self.copy_counters(slug)
        self.copy_events(slug)
        self.copy_decisions(slug)
        self.copy_chain_runs(slug, tasks)


# --------------------------------------------------------------------------- #
# Backend-specific helpers (the ONLY places with physical-schema knowledge)
# --------------------------------------------------------------------------- #
def _read_relations(src: Backend, slug: str, tasks: list) -> list:
    """Enumerate task<->task relations (no ``list_relations`` in the interface).

    Returns dicts ``{src_key, dst_key, kind}`` keyed by *human key* so they can
    be re-resolved on the destination (public_ids differ after copy). A None key
    means an endpoint task has no human key and cannot be remapped.
    """
    if src.is_pg:
        import sqlalchemy as sa
        from app.extensions import db
        from app.models import Project, Task, TaskRelation

        pid = db.session.execute(
            sa.select(Project.id).where(Project.slug == slug)
        ).scalar_one()
        rows = db.session.execute(
            sa.select(Task).where(Task.project_id == pid)
        ).scalars().all()
        id_to_key = {t.id: t.key for t in rows}
        ids = set(id_to_key)
        rels = db.session.execute(sa.select(TaskRelation)).scalars().all()
        out = []
        for r in rels:
            if r.src_task_id in ids and r.dst_task_id in ids:
                out.append({
                    "src_key": id_to_key[r.src_task_id],
                    "dst_key": id_to_key[r.dst_task_id],
                    "kind": r.kind.value,
                })
        return out

    # dynamodb
    from boto3.dynamodb.conditions import Attr, Key
    from app.storage import keys as K

    pub_to_key = {t.public_id: t.key for t in tasks}
    items = src.impl._query(
        KeyConditionExpression=Key("PK").eq(K.pk(slug)) & Key("SK").begins_with("TASK#"),
        FilterExpression=Attr("type").eq("relation"),
    )
    out = []
    for it in items:
        out.append({
            "src_key": pub_to_key.get(it.get("src")),
            "dst_key": pub_to_key.get(it.get("dst")),
            "kind": it["kind"],
        })
    return out


def _read_chain_runs(src: Backend, slug: str, tasks: list) -> list:
    """Enumerate chain runs + their steps (no ``list_chain_runs`` in interface).

    Returns dicts ``{task_key, started_by, status, steps:[...]}``. task_key is
    the run's task human key (None if the task is keyless -> unmappable).
    """
    if src.is_pg:
        import sqlalchemy as sa
        from app.extensions import db
        from app.models import ChainRun, ChainStep, Project, Task

        pid = db.session.execute(
            sa.select(Project.id).where(Project.slug == slug)
        ).scalar_one()
        runs = db.session.execute(
            sa.select(ChainRun).where(ChainRun.project_id == pid)
        ).scalars().all()
        out = []
        for run in runs:
            task = db.session.get(Task, run.task_id)
            task_key = task.key if task else None
            steps = db.session.execute(
                sa.select(ChainStep).where(ChainStep.run_id == run.id)
                .order_by(ChainStep.step_order)
            ).scalars().all()
            out.append({
                "task_key": task_key,
                "started_by": run.started_by,
                "status": run.status,
                "steps": [{
                    "step_name": s.step_name, "step_order": s.step_order,
                    "agent": s.agent, "status": s.status,
                    "skip_justification": s.skip_justification,
                    "output_ref": s.output_ref,
                } for s in steps],
            })
        return out

    # dynamodb
    from boto3.dynamodb.conditions import Key
    from app.storage import keys as K
    from app.storage.dynamo import _pyify

    pub_to_key = {t.public_id: t.key for t in tasks}
    items = src.impl._query(
        KeyConditionExpression=Key("PK").eq(K.pk(slug)) & Key("SK").begins_with("CRUN#"),
    )
    runs, steps_by_run = {}, {}
    for it in items:
        if it.get("type") == "chain_run":
            runs[it["public_id"]] = it
        elif it.get("type") == "chain_step":
            steps_by_run.setdefault(it["run"], []).append(it)
    out = []
    for pubid, run in runs.items():
        steps = sorted(steps_by_run.get(pubid, []),
                       key=lambda s: int(_pyify(s.get("step_order", 0))))
        out.append({
            "task_key": pub_to_key.get(run.get("task")),
            "started_by": run.get("started_by"),
            "status": run.get("status"),
            "steps": [{
                "step_name": s["step_name"],
                "step_order": int(_pyify(s.get("step_order", 0))),
                "agent": s.get("agent"), "status": s["status"],
                "skip_justification": s.get("skip_justification"),
                "output_ref": s.get("output_ref"),
            } for s in steps],
        })
    return out


def _set_counter(dest: Backend, slug: str, namespace: str, value: int) -> None:
    """Set the dest counter to ``value`` (the source high-water mark), never
    lowering an existing one — so the dest's NEXT reserve_number continues past
    every value already handed out on the source."""
    if dest.is_pg:
        import sqlalchemy as sa
        from app.extensions import db
        from app.models import Counter, Project

        pid = db.session.execute(
            sa.select(Project.id).where(Project.slug == slug)
        ).scalar_one()
        counter = db.session.get(Counter, (pid, namespace))
        if counter is None:
            db.session.add(Counter(project_id=pid, namespace=namespace,
                                   current_value=value))
        elif value > counter.current_value:
            counter.current_value = value
        db.session.commit()
        return

    # dynamodb — the counter item only needs current_value (namespace is in SK)
    from app.storage import keys as K
    from app.storage.dynamo import _pyify

    existing = dest.impl._get(K.pk(slug), K.counter_sk(namespace))
    current = int(_pyify(existing["current_value"])) if existing else 0
    if value > current:
        dest.impl._put({
            "PK": K.pk(slug), "SK": K.counter_sk(namespace),
            "type": "counter", "current_value": int(value),
        })


def _write_reservation(dest: Backend, slug: str, namespace: str, value: int,
                       reserved_by, note, created_at) -> str:
    """Insert an audit reservation row with its ORIGINAL value (idempotent by
    (namespace, value)). Returns "copied" or "skipped"."""
    if dest.is_pg:
        import sqlalchemy as sa
        from app.extensions import db
        from app.models import Project, Reservation

        pid = db.session.execute(
            sa.select(Project.id).where(Project.slug == slug)
        ).scalar_one()
        exists = db.session.execute(
            sa.select(Reservation.id).where(
                Reservation.project_id == pid,
                Reservation.namespace == namespace,
                Reservation.value == value,
            )
        ).scalar_one_or_none()
        if exists is not None:
            return "skipped"
        db.session.add(Reservation(
            project_id=pid, namespace=namespace, value=value,
            reserved_by=reserved_by, note=note, created_at=created_at,
        ))
        db.session.commit()
        return "copied"

    # dynamodb
    from app.storage import keys as K

    sk = K.reservation_sk(namespace, value)
    if dest.impl._get(K.pk(slug), sk) is not None:
        return "skipped"
    dest.impl._put({
        "PK": K.pk(slug), "SK": sk, "type": "reservation",
        "namespace": namespace, "value": int(value),
        "reserved_by": reserved_by, "note": note,
        "created_at": created_at.isoformat() if created_at else None,
    })
    return "copied"


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #
def _parse_args(argv=None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="copy_backend.py",
        description="Copy/sync a Spec Server backlog between storage backends "
                    "(postgres <-> dynamodb).",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=_EPILOG,
    )
    parser.add_argument("--source", required=True,
                        choices=["postgres", "dynamodb"],
                        help="source backend to read from")
    parser.add_argument("--dest", required=True,
                        choices=["postgres", "dynamodb"],
                        help="destination backend to write to")
    scope = parser.add_mutually_exclusive_group(required=True)
    scope.add_argument("--project", metavar="SLUG",
                       help="copy a single project by slug")
    scope.add_argument("--all", action="store_true",
                       help="copy every project on the source")
    parser.add_argument("--dry-run", action="store_true",
                        help="read the source only and report what WOULD copy")
    parser.add_argument("-v", "--verbose", action="store_true",
                        help="log per-project progress to stderr")
    return parser.parse_args(argv)


_EPILOG = """\
environment:
  postgres side:  SRC_DATABASE_URL / DEST_DATABASE_URL
  dynamodb side:  SRC_DYNAMODB_TABLE / DEST_DYNAMODB_TABLE          (default spec-server)
                  SRC_DYNAMODB_ENDPOINT_URL / DEST_DYNAMODB_ENDPOINT_URL  (DynamoDB Local)
                  SRC_AWS_REGION / DEST_AWS_REGION                  (default AWS_REGION/us-east-1)
                  AWS creds via the ambient boto3 chain (shared by both dynamo sides)

examples:
  python scripts/copy_backend.py --source postgres --dest dynamodb --project spec-server --dry-run
  python scripts/copy_backend.py --source postgres --dest dynamodb --project spec-server
  python scripts/copy_backend.py --source dynamodb --dest postgres --all

notes:
  * at most one side may be postgres (one global SQLAlchemy session per process);
    a postgres->postgres copy is a pg_dump/pg_restore job and is refused.
  * --dry-run never writes. A real run upserts by key and never deletes; append-only
    notes/events/decisions and keyless tasks are NOT de-duplicated on a re-run.
  * public_id/version/timestamps/owner/lease are regenerated or dropped by the dest
    (see the module docstring for the exact preservation table).
"""


def main(argv=None) -> int:
    args = _parse_args(argv)

    if args.source == "postgres" and args.dest == "postgres":
        sys.exit(
            "error: postgres->postgres is unsupported (single global SQLAlchemy "
            "session per process). Use pg_dump/pg_restore for a Postgres copy."
        )
    if args.source == args.dest:
        print("warning: source and dest backend kinds are identical — ensure "
              "their connection config differs.", file=sys.stderr)

    report = Report(dry_run=args.dry_run)
    src = None
    dest = None
    try:
        src = build_backend("source", args.source)
        # In --dry-run we never write, but we still build the dest so its config
        # is validated up front (cheap, and no writes are ever issued).
        dest = build_backend("dest", args.dest)

        copier = Copier(src, dest, report, verbose=args.verbose)

        if args.project:
            slugs = [args.project]
        else:
            slugs = [p.slug for p in src.impl.list_projects()]

        if not slugs:
            print("no projects found on the source; nothing to do.")
            return 0

        print(f"{'DRY-RUN: ' if args.dry_run else ''}"
              f"copying {len(slugs)} project(s) "
              f"{args.source} -> {args.dest}: {', '.join(slugs)}")

        for slug in slugs:
            try:
                copier.copy_project_all(slug)
            except Exception as exc:  # noqa: BLE001 — one bad project must not abort all
                report.warn(f"project {slug}: aborted ({type(exc).__name__}: {exc})")
                print(f"error: project {slug} aborted: {exc}", file=sys.stderr)

        print()
        print(report.render())
        total_failed = sum(s.failed for s in report.stats.values())
        return 1 if total_failed else 0
    finally:
        # Pop any pushed Flask app context (postgres side).
        for b in (dest, src):
            if b is not None and b.ctx is not None:
                try:
                    b.ctx.pop()
                except Exception:  # noqa: BLE001
                    pass


if __name__ == "__main__":
    raise SystemExit(main())
